### ISSUE TITLE
Fix multiple reiterations of "programación", Fix "Framework" translation

### ISSUE THREAD

**Issue by colemancda** [colemancda/Swift-Espanol#1]
Its not proper to reiterate the word so many times.

**Comment by ang182** [comment]
you shouldn't translate 'mature frameworks' as 'librerias maduras' im changing it  for marco operativo, i believe it's more accurate

**Comment by colemancda** [comment]
Here is the original text: 

“About Swift

Swift is a new programming language for iOS, OS X, watchOS, and tvOS apps that builds on the best of C and Objective-C, without the constraints of C compatibility. Swift adopts safe programming patterns and adds modern features to make programming easier, more flexible, and more fun. Swift’s clean slate, backed by the mature and much-loved Cocoa and Cocoa Touch frameworks, is an opportunity to reimagine how software development works.

Swift has been years in the making. Apple laid the foundation for Swift by advancing our existing compiler, debugger, and framework infrastructure. We simplified memory management with Automatic Reference Counting (ARC). Our framework stack, built on the solid base of Foundation and Cocoa, has been modernized and standardized throughout. Objective-C itself has evolved to support blocks, collection literals, and modules, enabling framework adoption of modern language technologies without disruption. Thanks to this groundwork, we can now introduce a new language for the future of Apple software development.

Swift feels familiar to Objective-C developers. It adopts the readability of Objective-C’s named parameters and the power of Objective-C’s dynamic object model. It provides seamless access to existing Cocoa frameworks and mix-and-match[…]”

Excerpt From: Apple Inc. “The Swift Programming Language (Swift 2.2).” iBooks.

**Comment by santos88** [comment]
si dejamos framework como framework??

**Comment by colemancda** [comment]
@santos88 Aqui esta la pagina de Wikipedia sobre [Framework](https://es.wikipedia.org/wiki/Framework). Lo que deseo es q alguien sin experiencia de desarrollo de software pueda entender el concepto. Entonces me parece mejor ponerlo en Espanol, y entre paréntesis ponerlo en Ingles, con link a Wikipedia.

**Comment by colemancda** [comment]
@ang182 @santos88 @CoderPug marco de trabajo podría ser?

**Comment by cegonya** [comment]
'Marco de Trabajo' en Español, pero siempre he usado 'Framework'

**Comment by enietom** [comment]
+1 a usar "framework". "mature frameworks" = "frameworks maduros"

"marcos de trabajo maduros" también sería una opción, pero "framework" me parece que es más usado en la documentación en español.

**Comment by santos88** [comment]
les parece si hacemos un wiki definiendo estos terminos para que en el
futuro no hayan las mismas dudas nuevamente

2015-12-30 13:16 GMT-03:00 Eduardo Nieto notifications@github.com:

**Comment by colemancda** [comment]
Estaba pensando lo mismo. Un glosario. PR?

```
Coleman,
```

**Comment by colemancda** [comment]
@santos88 Un glosario en un archivo MarkDown (`.md`) o usamos el Wiki de Github? Yo prefiero algo bajo version control.

**Comment by colemancda** [comment]
Y si usamos "librerías"? Ahorita lo puse asi:

"La implementacion nueva y limpia de Swift, apoyado por los [marcos de trabajo](https://es.wikipedia.org/wiki/Framework) (_framework_) de [_Cocoa_](https://es.wikipedia.org/wiki/Cocoa_%28informática%29) y [_Cocoa Touch_](https://es.wikipedia.org/wiki/Cocoa_Touch), es una oportunidad para reimaginar como funciona el desarollo de Software."

La idea es q la palabra en ingles (o español?) tendría un link al glosario. En el glosario habria la definición en ingles, y link aa su artículo en Wikipedia.

**Comment by colemancda** [comment]
Defined in glossary. Any changes to this term will be considered as a pull request to the [glossary](glossary.md).
