### ISSUE TITLE
Dudas

### ISSUE THREAD

**Issue by santos88** [colemancda/Swift-Espanol#4]
Estimados he estado traduciendo partes de la guía pero tomando como referencia

https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/TheBasics.html#//apple_ref/doc/uid/TP40014097-CH5-ID309

luego hoy vi los cambios agregados y me di con la sorpresa que estaban usando
https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/GuidedTour.html#//apple_ref/doc/uid/TP40014097-CH2-ID1

Si lo que estamos traduciendo es A Swift Tour, eso debería estar dentro del documento, por otra parte sería ideal si usamos algun formato para colocar la referencia de la fuente de ese documento a traducir

algo asi:
# Bienvenidos a Swift

Original: http://apple.com/url_del_documento_original

**Comment by colemancda** [comment]
@santos88 estoy traduciendo la version ePub que se encuentra en [Swift.org](www.swift.org). Esa es open source y la mas nueva.

https://swift.org/documentation/

El objectivo aqui es hacer una buena traducción, profesional y que Apple puede añadir una link en su pagina www.swift.org para la comunidad hispanohablante.
